import { Layout } from '../components/layout/Layout';
import { SEO } from '../components/layout/SEO';

const sections = [
  {
    title: 'Information we may receive',
    items: [
      'Name, email address and message content when you choose to contact us directly',
      'Company or project information that you voluntarily include in an enquiry',
      'Limited technical request or security logs generated by hosting and infrastructure services, which may include browser, device, requested page, timestamp or network information',
    ],
  },
  {
    title: 'How information is used',
    items: [
      'To respond to enquiries and project discussions',
      'To operate, secure and troubleshoot the website',
      'To improve website content and product communication',
      'To communicate about products or services when appropriate to the enquiry',
    ],
  },
];

export const PrivacyPolicy = () => (
  <Layout>
    <SEO title="Privacy Policy | Third Leap Labs LLC" description="Privacy policy outlining how Third Leap Labs LLC handles website enquiries and limited technical information." path="/privacy-policy" />
    <main className="site-page pt-16">
      <section className="border-b border-[#2D3142]/15 bg-[#F8F6F7]">
        <div className="page-shell py-14 sm:py-16">
          <span className="kicker">Legal</span>
          <h1 className="section-display mt-5">Privacy policy</h1>
          <p className="copy-md mt-5 max-w-[760px]">Third Leap Labs LLC aims to collect only the information needed to operate the website, maintain security and respond to people who choose to contact us.</p>
        </div>
      </section>

      <section className="bg-white py-14 lg:py-16">
        <div className="page-shell max-w-[980px]">
          <div className="border-b border-[#2D3142]/20 pb-5"><p className="mono text-[10px] uppercase tracking-[.06em] text-[#4F5D75]">Last reviewed / August 2026</p></div>
          <div>
            {sections.map((section, index) => (
              <section key={section.title} className="grid gap-4 border-b border-[#2D3142]/15 py-8 sm:grid-cols-[48px_1fr] sm:gap-7">
                <span className="mono text-[10px] text-[#4F5D75]">0{index + 1}</span>
                <div>
                  <h2 className="text-[22px] font-semibold tracking-[-.035em] text-[#2D3142]">{section.title}</h2>
                  <ul className="mt-5 space-y-3">
                    {section.items.map((item) => (
                      <li key={item} className="flex items-start gap-3 text-[14px] leading-7 text-[#4F5D75]">
                        <span className="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-[#1DA1F2]" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
              </section>
            ))}

            <section className="grid gap-4 border-b border-[#2D3142]/15 py-8 sm:grid-cols-[48px_1fr] sm:gap-7">
              <span className="mono text-[10px] text-[#4F5D75]">03</span>
              <div><h2 className="text-[22px] font-semibold tracking-[-.035em]">What we do not request through this website</h2><p className="mt-4 text-[14px] leading-7 text-[#4F5D75]">The website does not use a project-enquiry form database. Third Leap Labs does not ask visitors to submit seed phrases, private keys, wallet recovery phrases, production passwords or other sensitive credentials through the website.</p></div>
            </section>

            <section className="grid gap-4 border-b border-[#2D3142]/15 py-8 sm:grid-cols-[48px_1fr] sm:gap-7">
              <span className="mono text-[10px] text-[#4F5D75]">04</span>
              <div><h2 className="text-[22px] font-semibold tracking-[-.035em]">Third-party services</h2><p className="mt-4 text-[14px] leading-7 text-[#4F5D75]">The website may rely on third-party hosting, DNS, email, code-hosting or infrastructure services. Those providers may process limited technical or communications data under their own terms and privacy policies.</p></div>
            </section>

            <section className="grid gap-4 py-8 sm:grid-cols-[48px_1fr] sm:gap-7">
              <span className="mono text-[10px] text-[#4F5D75]">05</span>
              <div><h2 className="text-[22px] font-semibold tracking-[-.035em]">Contact</h2><p className="mt-4 text-[14px] leading-7 text-[#4F5D75]">For privacy-related questions, contact <a href="mailto:hello@thirdleaplabs.com" className="font-semibold text-[#1DA1F2] hover:underline">hello@thirdleaplabs.com</a>.</p></div>
            </section>
          </div>
        </div>
      </section>
    </main>
  </Layout>
);
